name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typst
        uses: lvignoli/typst-action@v0
        with:
          source_file: |
            masodik_zh_def.typ
            masodik_zh_tetel.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: |
            masodik_zh_def.pdf
            masodik_zh_tetel.pdf
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - uses: "marvinpinto/action-automatic-releases@latest"
        name: Release
        with:
          repo_token: "${{ secrets.PAT }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Bugfix"
          files: |
            masodik_zh_def.pdf
            masodik_zh_tetel.pdf
